version: "3.8"

services:
  database:
    container_name: database
    image: mariadb:10
    ports:
      - 3308:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
    
  app:
    container_name: arrangingseats-app
    image: openjdk:17-alpine
    ports:
      - "8085:8085"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./gradlew", "bootrun"]
    networks:
      - backend
    depends_on:
      - database
    restart: always

networks:
  backend:
